### ISSUE TITLE
missing release

### ISSUE THREAD

**Issue by xenDE** [niorad/Skewbacca-Native#1]
hi,

nice little tool.

why no binary version?

would be great to see a release working osx 10.13 :)

best regards,
daniel

seen min 11:00 here: https://www.twitch.tv/videos/630888724

**Comment by niorad** [comment]
Hi, thanks for watching!
This tool isn't meant to be used by anybody else. Also I only have 10.15, so I can't test 10.13. Feel free to clone and build it yourself, I didn't use any external dependencies, so it should be quick to open in XCode and press "play". I just tried it and it works fine.

**Comment by xenDE** [comment]
ok, thanks.

it's running, but the edge selectors are only black squares.

![grafik](https://user-images.githubusercontent.com/2836430/82809368-3d57dd80-9e8c-11ea-991c-21cb9d2f5687.png)

any ideas whats wrong here?

best regards,
daniel

**Comment by niorad** [comment]
In the main storyboard on the bottom left you can click the four crosses and set their images. Maybe the image-file got lost somehow.
https://www.dropbox.com/s/5wegaqch406rcv9/cross.png?dl=0
